import { QuestionBank, LessonConfig, GameLibrary, KahootQuestion, KahootGame, VocabEntry, VocabQuestion } from './types';

export const LESSONS: LessonConfig[] = [
  { id: 1, title: "10.1 A Question of Taste", color: "text-orange-500", gradient: "from-orange-500 to-red-500", icon: "🍋" },
  { id: 2, title: "10.2 Canned Dreams", color: "text-purple-500", gradient: "from-purple-500 to-pink-500", icon: "🥫" },
  { id: 3, title: "10.3 Food Waste", color: "text-teal-500", gradient: "from-teal-400 to-emerald-600", icon: "♻️" },
  { id: 4, title: "10.4 Restaurant Problems", color: "text-red-500", gradient: "from-red-500 to-rose-400", icon: "🍽️" },
  { id: 5, title: "10.5 Vocabulary Master", color: "text-indigo-500", gradient: "from-indigo-500 to-blue-500", icon: "📚" },
];

export const PERSONALITY_TIPS = {
    introvert: "Tip: Give 30s silence before asking for hands. Allow use of the Scratchpad.",
    extrovert: "Tip: Channel energy into the Reaction Bar. Use Debate Randomizer for fast finishers.",
    ambivert: "Tip: Use the Think-Pair-Share timer to ensure balanced participation."
};

export const VOCAB_DATA: VocabEntry[] = [
  { word: "alcoholic drink", type: "n", phonetic: "/ˌælkəˈhɒlɪk drɪŋk/", ru: "алкогольный напиток", uz: "alkogolli ichimlik", example: "Wine is an alcoholic drink." },
  { word: "apple juice", type: "n", phonetic: "/ˈæpl dʒuːs/", ru: "яблочный сок", uz: "olma sharbati", example: "I drink apple juice for breakfast." },
  { word: "bake", type: "v", phonetic: "/beɪk/", ru: "печь, выпекать", uz: "pishirmoq (duxovkada)", example: "They're baked in the oven." },
  { word: "best before", type: "n", phonetic: "/ˌbest bɪˈfɔː(r)/", ru: "годен до", uz: "yaroqlilik muddati", example: "A 'best before' label tells you about quality." },
  { word: "bitter", type: "adj", phonetic: "/ˈbɪtə(r)/", ru: "горький", uz: "achchiq (ta'm)", example: "I don't like it. It's got a very bitter taste." },
  { word: "boiled", type: "adj", phonetic: "/bɔɪld/", ru: "вареный", uz: "qaynatilgan", example: "I don't like boiled vegetables." },
  { word: "bottle", type: "n", phonetic: "/ˈbɒtl/", ru: "бутылка", uz: "shisha", example: "Let's get a bottle of sparkling water." },
  { word: "box", type: "n", phonetic: "/bɒks/", ru: "коробка", uz: "quti", example: "We bought a box of chocolates." },
  { word: "can", type: "n", phonetic: "/kæn/", ru: "жестяная банка", uz: "konserva bankasi", example: "Can I have a can of lemonade?" },
  { word: "cardboard", type: "n", phonetic: "/ˈkɑːdbɔːd/", ru: "картон", uz: "karton", example: "This container is made from cardboard." },
  { word: "carton", type: "n", phonetic: "/ˈkɑːtn/", ru: "картонная коробка (пакет)", uz: "quti (qog'oz)", example: "There's a carton of juice in the fridge." },
  { word: "charge", type: "v", phonetic: "/tʃɑːdʒ/", ru: "брать плату", uz: "haq olmoq", example: "Supermarkets charge for bags." },
  { word: "chocolate", type: "n", phonetic: "/ˈtʃɒklət/", ru: "шоколад", uz: "shokolad", example: "He gave me chocolates for my birthday." },
  { word: "consumer", type: "n", phonetic: "/kənˈsjuːmə(r)/", ru: "потребитель", uz: "iste'molchi", example: "Consumers are responsible for waste." },
  { word: "curry", type: "n", phonetic: "/ˈkʌri/", ru: "карри", uz: "karri", example: "Most curry dishes are spicy." },
  { word: "dessert", type: "n", phonetic: "/dɪˈzɜːt/", ru: "десерт", uz: "shirinlik", example: "Would you like some cake for dessert?" },
  { word: "different", type: "adj", phonetic: "/ˈdɪfrənt/", ru: "разный, другой", uz: "turli xil", example: "There are many different sorts of rolls." },
  { word: "dish", type: "n", phonetic: "/dɪʃ/", ru: "блюдо", uz: "taom", example: "I usually serve this dish with vegetables." },
  { word: "doggy bag", type: "n", phonetic: "/ˈdɒɡi bæɡ/", ru: "пакет для остатков еды", uz: "ovqat qoldiqlari uchun paket", example: "Ask the waiter for a doggy bag." },
  { word: "figure", type: "n", phonetic: "/ˈfɪɡə(r)/", ru: "цифра", uz: "raqam", example: "It's a figure of a man." },
  { word: "flavour", type: "n", phonetic: "/ˈfleɪvə(r)/", ru: "вкус, аромат", uz: "ta'm, hid", example: "Dip them in sauce for extra flavour." },
  { word: "frozen", type: "adj", phonetic: "/ˈfrəʊzn/", ru: "замороженный", uz: "muzlatilgan", example: "I need a packet of frozen peas." },
  { word: "fry", type: "v", phonetic: "/fraɪ/", ru: "жарить", uz: "qovurmoq", example: "Sometimes the spring rolls are fried." },
  { word: "funny", type: "adj", phonetic: "/ˈfʌni/", ru: "смешной, странный", uz: "kulgili, g'alati", example: "A funny thing happened to me." },
  { word: "herb", type: "n", phonetic: "/hɜːb/", ru: "трава (приправа)", uz: "ko'kat", example: "There are lots of herbs in this stew." },
  { word: "honey", type: "n", phonetic: "/ˈhʌni/", ru: "мёд", uz: "asal", example: "The tagine has honey in it." },
  { word: "jar", type: "n", phonetic: "/dʒɑː(r)/", ru: "стеклянная банка", uz: "banka", example: "Could you buy a jar of olives?" },
  { word: "kind of", type: "phr", phonetic: "/kaɪnd əv/", ru: "разновидность, типа", uz: "bir turi", example: "It's a kind of stew." },
  { word: "lamb", type: "n", phonetic: "/læm/", ru: "ягнятина", uz: "qo'zi go'shti", example: "This tagine is made with lamb." },
  { word: "leave", type: "v", phonetic: "/liːv/", ru: "оставлять", uz: "qoldirmoq", example: "I've left some cake for you." },
  { word: "left", type: "adj", phonetic: "/left/", ru: "левый", uz: "chap", example: "We took a left turn." },
  { word: "mark", type: "n", phonetic: "/mɑːk/", ru: "оценка", uz: "baho", example: "What mark did you get in the test?" },
  { word: "olives", type: "n", phonetic: "/ˈɒlɪvz/", ru: "оливки", uz: "zaytun", example: "Would you like some olives?" },
  { word: "packet", type: "n", phonetic: "/ˈpækɪt/", ru: "пакет, пачка", uz: "paket, pachka", example: "A packet of frozen peas." },
  { word: "plain", type: "adj", phonetic: "/pleɪn/", ru: "простой, без добавок", uz: "oddiy, qo'shimchasiz", example: "I prefer plain food." },
  { word: "preserve", type: "v", phonetic: "/prɪˈzɜːv/", ru: "сохранять", uz: "saqlamoq", example: "His invention preserved food." },
  { word: "pretty", type: "adj", phonetic: "/ˈprɪti/", ru: "симпатичная", uz: "chiroyli", example: "She's a very pretty woman." },
  { word: "pretty", type: "adv", phonetic: "/ˈprɪti/", ru: "довольно", uz: "ancha", example: "It's pretty expensive." },
  { word: "raspberry", type: "n", phonetic: "/ˈrɑːzbəri/", ru: "малина", uz: "malina", example: "Would you like raspberries?" },
  { word: "raw", type: "adj", phonetic: "/rɔː/", ru: "сырой", uz: "xom", example: "They're filled with raw vegetables." },
  { word: "sauce", type: "n", phonetic: "/sɔːs/", ru: "соус", uz: "sous", example: "Dip it into this sauce." },
  { word: "savoury", type: "adj", phonetic: "/ˈseɪvəri/", ru: "пикантный, несладкий", uz: "sho'rtak, mazali", example: "Do you prefer sweet or savoury food?" },
  { word: "serve", type: "v", phonetic: "/sɜːv/", ru: "подавать", uz: "tortmoq (taom)", example: "This dish is often served with rice." },
  { word: "several", type: "pron", phonetic: "/ˈsevrəl/", ru: "несколько", uz: "bir qancha", example: "There are several different vegetables." },
  { word: "shocking", type: "adj", phonetic: "/ˈʃɒkɪŋ/", ru: "шокирующий", uz: "dahshatli", example: "It's a pretty shocking figure." },
  { word: "snack", type: "n", phonetic: "/snæk/", ru: "перекус", uz: "yengil tamaddi", example: "I have a small snack at 11 a.m." },
  { word: "sour", type: "adj", phonetic: "/ˈsaʊə(r)/", ru: "кислый", uz: "nordon", example: "Lime juice makes it sour." },
  { word: "sparkling water", type: "n", phonetic: "/ˌspɑːklɪŋ ˈwɔːtə(r)/", ru: "газированная вода", uz: "gazli suv", example: "Can I have some sparkling water?" },
  { word: "spice", type: "n", phonetic: "/spaɪs/", ru: "специя", uz: "ziravor", example: "Made with lots of different spices." },
  { word: "spicy", type: "adj", phonetic: "/ˈspaɪsi/", ru: "острый", uz: "achchiq (qalampirli)", example: "Chilli makes it spicy." },
  { word: "spinach", type: "n", phonetic: "/ˈspɪnɪtʃ/", ru: "шпинат", uz: "ismaloq", example: "Spinach has a bitter taste." },
  { word: "stew", type: "n", phonetic: "/stjuː/", ru: "рагу", uz: "dimlama", example: "I'm making lamb stew." },
  { word: "strawberry", type: "n", phonetic: "/ˈstrɔːbəri/", ru: "клубника", uz: "qulupnay", example: "You put strawberry jam on them." },
  { word: "tagine", type: "n", phonetic: "/təˈʒiːn/", ru: "тажин", uz: "tajin (tuvakda pishgan taom)", example: "Tagine is a kind of stew." },
  { word: "taste", type: "n", phonetic: "/teɪst/", ru: "вкус", uz: "ta'm", example: "This has a nice, bitter taste." },
  { word: "taste buds", type: "n", phonetic: "/ˈteɪst bʌdz/", ru: "вкусовые рецепторы", uz: "ta'm bilish retseptorlari", example: "It depends on the taste buds on your tongue." },
  { word: "texture", type: "n", phonetic: "/ˈtekstʃə(r)/", ru: "текстура", uz: "to'qima", example: "I love the different textures." },
  { word: "thick", type: "adj", phonetic: "/θɪk/", ru: "густой, толстый", uz: "quyuq, qalin", example: "This is quite a thick sauce." },
  { word: "tin", type: "n", phonetic: "/tɪn/", ru: "консервная банка", uz: "konserva", example: "I'm going to use a tin of tomatoes." },
  { word: "tobacco", type: "n", phonetic: "/təˈbækəʊ/", ru: "табак", uz: "tamaki", example: "Tobacco has a strong taste." },
  { word: "tomato", type: "n", phonetic: "/təˈmɑːtəʊ/", ru: "помидор", uz: "pomidor", example: "We need some tomatoes for salad." },
  { word: "toothpaste", type: "n", phonetic: "/ˈtuːθpeɪst/", ru: "зубная паста", uz: "tish pastasi", example: "I need to buy a tube of toothpaste." },
  { word: "transportation", type: "n", phonetic: "/ˌtrænspɔːˈteɪʃn/", ru: "транспортировка", uz: "tashish", example: "Waste happens during transportation." },
  { word: "tube", type: "n", phonetic: "/tjuːb/", ru: "тюбик", uz: "tyubik", example: "Did you pack a tube of toothpaste?" },
  { word: "use by", type: "n", phonetic: "/ˈjuːz baɪ/", ru: "использовать до", uz: "gacha foydalanish", example: "Check the 'use by' date." },
  { word: "wasteful", type: "adj", phonetic: "/ˈweɪstfl/", ru: "расточительный", uz: "isrofgar", example: "People are not as wasteful as they are today." }
];

export const VOCAB_QUESTIONS: VocabQuestion[] = [
  { q: "What **snack** do you buy when you play games or scroll social media?", a: "I usually buy a **snack** like **chocolate**. **Reasons:** It is quick and it gives me energy. **Examples:** I eat a small **packet** after school while I watch YouTube." },
  { q: "Do you prefer **sparkling water** or juice?", a: "I prefer **sparkling water**. **Reasons:** It tastes fresh and it isn’t too sweet. **Examples:** I drink a **bottle** of **sparkling water** after football." },
  { q: "What do you drink at breakfast: **apple juice** or tea?", a: "I often drink **apple juice**. **Reasons:** It is sweet and easy to make. **Examples:** I buy a **carton** of **apple juice** and keep it in the fridge." },
  { q: "Do you like **spicy** food or **plain** food?", a: "I like **spicy** food. **Reasons:** The **spice** gives strong **flavour**. **Examples:** I eat **curry** with rice when I’m really hungry." },
  { q: "What **dish** do you eat with your family on weekends?", a: "We usually eat one special **dish** together. **Reasons:** It feels warm and family-like. **Examples:** My mum makes a **stew** and we **serve** it with bread." },
  { q: "When you go to a café, do you ask for a **doggy bag** sometimes?", a: "Yes, I ask for a **doggy bag** sometimes. **Reasons:** I don’t want to be **wasteful**. **Examples:** If I can’t finish dessert, I take it home." },
  { q: "Do you ever **bake** food at home?", a: "Yes, I sometimes **bake** simple food. **Reasons:** It is easy and healthier than **fry**. **Examples:** I **bake** potatoes and they taste great with **sauce**." },
  { q: "Do you like **boiled** vegetables?", a: "Not really, I don’t like **boiled** vegetables. **Reasons:** The **texture** feels too soft. **Examples:** I prefer **raw** carrots with a little **sauce**." },
  { q: "What is your favourite **dessert**?", a: "My favourite **dessert** is ice cream with fruit. **Reasons:** It is sweet and refreshing. **Examples:** I add **strawberry** or **raspberry** on top." },
  { q: "Do you like **bitter** tastes?", a: "No, I don’t like **bitter** tastes. **Reasons:** My **taste buds** don’t enjoy it. **Examples:** I don’t like very dark chocolate because it tastes **bitter**." },
  { q: "What do you usually buy in a **box**?", a: "I sometimes buy sweets in a **box**. **Reasons:** It is good for sharing with friends. **Examples:** I bring a **box** of **chocolate** to birthdays." },
  { q: "What do you usually buy in a **can**?", a: "I sometimes buy a drink in a **can**. **Reasons:** It is cheap and easy to carry. **Examples:** I buy a **can** of lemonade on hot days." },
  { q: "What do you keep in a **jar** at home?", a: "We keep some food in a **jar**. **Reasons:** It stays clean and safe. **Examples:** We have a **jar** of **honey** or **olives**." },
  { q: "Do shops in your city **charge** for bags?", a: "Yes, many shops **charge** for bags. **Reasons:** They want less plastic and less waste. **Examples:** If you forget your bag, they **charge** you at the checkout." },
  { q: "Do you often buy **frozen** food?", a: "Yes, I sometimes buy **frozen** food. **Reasons:** It is fast and easy for busy days. **Examples:** I buy a **packet** of **frozen** peas." },
  { q: "What is your favourite sauce?", a: "My favourite **sauce** is garlic sauce. **Reasons:** It adds strong **flavour**. **Examples:** I dip fries into **sauce** when I eat fast food." },
  { q: "What do you think is a **shocking** thing on social media?", a: "Some videos are **shocking**. **Reasons:** People do dangerous things for likes. **Examples:** I see a **shocking figure** like “1 million views in 1 hour.”" },
  { q: "Do you like **sour** tastes?", a: "Yes, I like **sour** tastes sometimes. **Reasons:** It feels fresh and fun. **Examples:** I drink lemon **juice** and it tastes **sour**." },
  { q: "What **kind of** games do you play?", a: "I play a **kind of** team game. **Reasons:** It is more fun with friends. **Examples:** We play shooters and we talk on Discord." },
  { q: "Do you like **savoury** snacks or sweet snacks?", a: "I like **savoury** snacks more. **Reasons:** Sweet things get boring quickly. **Examples:** I eat chips with **spice** and **sauce**." },
  { q: "What food do you think has the best **texture**?", a: "I think pizza has great **texture**. **Reasons:** It is soft and a bit crispy. **Examples:** The cheese is **thick** and the crust is crunchy." },
  { q: "Do you ever look at the **best before** date?", a: "Yes, I check the **best before** date. **Reasons:** I want good quality food. **Examples:** I check the milk and yogurt before I buy them." },
  { q: "Do you ever check the **use by** date?", a: "Yes, I check the **use by** date carefully. **Reasons:** It is about safety. **Examples:** I check meat and eggs for the **use by** date." },
  { q: "Do you think people are more **wasteful** today?", a: "Yes, people are more **wasteful** today. **Reasons:** They buy too much and throw food away. **Examples:** Some people leave food and don’t take a **doggy bag**." },
  { q: "What drink do you buy in a **bottle**?", a: "I often buy water in a **bottle**. **Reasons:** It is easy for school. **Examples:** I buy a **bottle** of **sparkling water**." },
  { q: "What do you think about **alcoholic drink** ads online?", a: "I don’t like **alcoholic drink** ads for teens. **Reasons:** They can influence young people. **Examples:** I report ads when I see them on social media." },
  { q: "What **herb** do you like in food?", a: "I like the **herb** basil. **Reasons:** It makes food smell nice. **Examples:** I add this **herb** to pasta with tomato **sauce**." },
  { q: "Do you like **honey** in tea?", a: "Yes, I like **honey** in tea. **Reasons:** It tastes sweet and feels healthy. **Examples:** When I have a cold, I drink tea with **honey**." },
  { q: "Do you eat **olives**?", a: "Yes, I eat **olives** sometimes. **Reasons:** They have a strong taste. **Examples:** I eat **olives** from a **jar** with salad." },
  { q: "What’s your favourite **tomato** food?", a: "I like pasta with **tomato** **sauce**. **Reasons:** It tastes rich and simple. **Examples:** I use a **tin** of **tomato** when we have no fresh ones." },
  { q: "Do you ever buy food in a **tin**?", a: "Yes, I buy food in a **tin** sometimes. **Reasons:** It lasts longer. **Examples:** I buy a **tin** of tomatoes for quick cooking." },
  { q: "Do you like **spinach**?", a: "Yes, I like **spinach** in some meals. **Reasons:** It is healthy and easy to cook. **Examples:** I put **spinach** in eggs or soup." },
  { q: "What do you usually put in your school bag: **toothpaste** or snacks?", a: "I sometimes pack **toothpaste** for trips. **Reasons:** I want to feel fresh. **Examples:** I pack a **tube** of **toothpaste** when I travel." },
  { q: "Do you prefer to **fry** or **bake** food?", a: "I prefer to **bake** food. **Reasons:** **Fry** uses more oil. **Examples:** I **bake** chicken and it still tastes great." },
  { q: "When do you usually have a **snack**?", a: "I have a **snack** in the afternoon. **Reasons:** I feel hungry after school. **Examples:** I eat a **packet** of nuts or a banana." },
  { q: "What is a **shocking figure** about online games?", a: "A **shocking figure** is how much money people spend. **Reasons:** Skins and packs are tempting. **Examples:** Some players spend $100 in one week." },
  { q: "Do you think you are a smart **consumer** online?", a: "I try to be a smart **consumer**. **Reasons:** Ads can trick people. **Examples:** I read reviews before I buy headphones." },
  { q: "What food has a strong **flavour** in your country?", a: "Plov has strong **flavour**. **Reasons:** It has meat, carrots, and **spice**. **Examples:** At weddings, we **serve** a big **dish** of plov." },
  { q: "Do you prefer **different** games or one game all the time?", a: "I like **different** games. **Reasons:** I get bored quickly. **Examples:** I play sports games, racing, and story games." },
  { q: "What do you do when you get a bad **mark** at school?", a: "I try to fix it after a bad **mark**. **Reasons:** I want to improve. **Examples:** I study more and ask my teacher for help." },
  { q: "What **kind of** food do you order with friends?", a: "We order a **kind of** fast food. **Reasons:** It is cheap and quick. **Examples:** We share pizza and **sparkling water**." },
  { q: "Do you like **raw** vegetables?", a: "Yes, I like **raw** vegetables. **Reasons:** They are crunchy and fresh. **Examples:** I eat **raw** carrots with **sauce**." },
  { q: "What is your favourite **dessert** to post on Instagram?", a: "I post colourful **dessert** photos. **Reasons:** People like sweet pictures. **Examples:** I post cake with **strawberry** on top." },
  { q: "Do you like **plain** food?", a: "Sometimes I like **plain** food. **Reasons:** After spicy meals, I need a break. **Examples:** I eat **plain** rice with a little **sauce**." },
  { q: "Do your parents ever **preserve** food at home?", a: "Yes, my family sometimes **preserve** food. **Reasons:** It saves money and it lasts longer. **Examples:** We **preserve** tomatoes in jars for winter." },
  { q: "Do you think it’s **pretty** easy to save money as a teen?", a: "No, it’s **pretty** hard. **Reasons:** Snacks and games cost money. **Examples:** If I buy a **snack** every day, I lose a lot." },
  { q: "Who is a **pretty** person you follow on social media?", a: "I follow some **pretty** influencers. **Reasons:** Their style and photos look nice. **Examples:** They post travel videos and outfits." },
  { q: "Do you like **thick** sauces?", a: "Yes, I like **thick** sauces. **Reasons:** They have strong **flavour**. **Examples:** I like a **thick** cheese **sauce** on pasta." },
  { q: "What is the best **dish** for a cold day?", a: "The best **dish** is **stew**. **Reasons:** It is warm and filling. **Examples:** We make a meat **stew** with herbs." },
  { q: "Do you like **curry**?", a: "Yes, I like **curry**. **Reasons:** It is **spicy** and tasty. **Examples:** I eat chicken **curry** with rice." },
  { q: "What’s your favourite fruit: **strawberry** or **raspberry**?", a: "I prefer **strawberry**. **Reasons:** It tastes sweeter. **Examples:** I add **strawberry** to yogurt as a **snack**." },
  { q: "Do you like the **taste** of energy drinks?", a: "Not really, I don’t like the **taste**. **Reasons:** It feels too sweet and strong. **Examples:** I choose **sparkling water** instead." },
  { q: "When you buy food, do you look at the **figure** (number) on the price tag?", a: "Yes, I look at the **figure**. **Reasons:** I must control my money. **Examples:** If the **figure** is high, I buy a cheaper **packet**." },
  { q: "What do you usually buy in a **carton**?", a: "I buy juice in a **carton**. **Reasons:** It is easy to store. **Examples:** I buy a **carton** of **apple juice**." },
  { q: "What do you think about **cardboard** packaging?", a: "I like **cardboard** packaging. **Reasons:** It is better for the environment. **Examples:** Many juices come in a **carton** made of **cardboard**." },
  { q: "Do you think it’s okay to **charge** extra for online delivery?", a: "Yes, it is okay to **charge** extra sometimes. **Reasons:** Delivery costs money. **Examples:** If the shop is far, they **charge** more." },
  { q: "What is your favourite **chocolate**?", a: "My favourite **chocolate** is milk chocolate. **Reasons:** It tastes sweet, not **bitter**. **Examples:** I buy a small bar as a **snack**." },
  { q: "Do you ever take leftover food home?", a: "Yes, I take it home. **Reasons:** I don’t want to be **wasteful**. **Examples:** I ask for a **doggy bag** after dinner." },
  { q: "What do you usually put in a **packet**?", a: "I buy snacks in a **packet**. **Reasons:** It is cheap and easy. **Examples:** I buy a **packet** of chips for game night." },
  { q: "Do you like food with many **spices**?", a: "Yes, I like food with **spice**. **Reasons:** It makes the **taste** interesting. **Examples:** I like **spicy** shawarma with garlic **sauce**." },
  { q: "Do you like **sour** candy?", a: "Yes, I like **sour** candy sometimes. **Reasons:** It feels fun and strong. **Examples:** My face changes because it tastes so **sour**." },
  { q: "What is a **funny** moment you share with friends?", a: "We share **funny** memes. **Reasons:** They make us laugh and relax. **Examples:** We send a **funny** video in our group chat." },
  { q: "Do you like **lamb**?", a: "Yes, I like **lamb** sometimes. **Reasons:** It tastes rich. **Examples:** My family cooks **lamb** in a **stew**." },
  { q: "Have you ever tried **tagine**?", a: "Yes, I try **tagine** once. **Reasons:** I like **different** food. **Examples:** It is a **kind of** **stew** with spices." },
  { q: "What is your favourite **dish** to **serve** guests?", a: "We **serve** plov to guests. **Reasons:** It is traditional and filling. **Examples:** We **serve** a big **dish** and everyone shares." },
  { q: "Do you have **several** close friends or just one best friend?", a: "I have **several** close friends. **Reasons:** I like meeting **different** people. **Examples:** We play games and travel together." },
  { q: "What do you usually **leave** at home when you go out?", a: "I sometimes **leave** my charger at home. **Reasons:** I forget easily. **Examples:** Then my phone dies and I can’t watch videos." },
  { q: "Do you prefer a sweet **dessert** or a **savoury** snack?", a: "I prefer sweet **dessert**. **Reasons:** It feels like a reward. **Examples:** I eat cake with **honey** or fruit." },
  { q: "Do you like **boiled** eggs or fried eggs?", a: "I like **boiled** eggs. **Reasons:** They are simple and healthy. **Examples:** I eat two **boiled** eggs for breakfast." },
  { q: "What food looks “Instagram-worthy” because it’s **pretty**?", a: "Cakes look very **pretty**. **Reasons:** They have bright colours and nice shapes. **Examples:** A strawberry cake with **sauce** looks amazing." },
  { q: "Do you like **frozen** dessert?", a: "Yes, I like **frozen** dessert. **Reasons:** It is cool in summer. **Examples:** I eat **frozen** ice cream after school." },
  { q: "What do you usually buy in a **bottle** for a trip?", a: "I buy water in a **bottle**. **Reasons:** I need hydration. **Examples:** On a bus trip, I drink **sparkling water**." },
  { q: "Do you think teens spend too much money on games?", a: "Yes, many teens spend too much. **Reasons:** They want skins and upgrades. **Examples:** They see a **shocking figure** on their bank app." },
  { q: "What **kind of** **transportation** do you use to school?", a: "I use public **transportation**. **Reasons:** It is cheaper than a taxi. **Examples:** I take the bus and walk 5 minutes." },
  { q: "What’s a healthy **snack** you like?", a: "I like fruit as a healthy **snack**. **Reasons:** It is natural and fresh. **Examples:** I eat a **strawberry** or **raspberry** yogurt." },
  { q: "Do you like **spinach** in salad?", a: "Yes, I like **spinach** in salad. **Reasons:** It tastes fresh and light. **Examples:** I eat **spinach** with **tomato** and olives." },
  { q: "Do you ever buy **toothpaste** because of a cool ad?", a: "Sometimes, yes. **Reasons:** Ads influence young **consumers**. **Examples:** I buy a new **tube** of **toothpaste** after I see an ad." },
  { q: "What food has the best **flavour** in your opinion?", a: "I think kebab has amazing **flavour**. **Reasons:** It has smoke, meat, and **spice**. **Examples:** I eat it with **sauce** and bread." },
  { q: "Do you like **plain** chips or **spicy** chips?", a: "I prefer **spicy** chips. **Reasons:** The **taste** is stronger. **Examples:** I buy a **packet** of hot chips." },
  { q: "What do you do if a product is past its **best before** date?", a: "I don’t buy it if it is past **best before**. **Reasons:** It may taste bad. **Examples:** I choose a fresher yogurt with a later date." },
  { q: "What do you do if something is past its **use by** date?", a: "I throw it away if it is past **use by**. **Reasons:** Safety is important. **Examples:** I don’t eat chicken after the **use by** date." },
  { q: "Do you like **raw** fish (like sushi)?", a: "Not really, I don’t like **raw** fish. **Reasons:** The **texture** feels strange to me. **Examples:** I prefer cooked fish or chicken." },
  { q: "What **different** food do you want to try while travelling?", a: "I want to try **different** food. **Reasons:** It is exciting and cultural. **Examples:** I want to try **tagine** and **curry**." },
  { q: "What do you think about people smoking **tobacco**?", a: "I don’t like **tobacco** smoking. **Reasons:** It smells bad and hurts health. **Examples:** I avoid places where people smoke **tobacco**." },
  { q: "What do you usually buy in a **tin** when you are busy?", a: "I buy soup in a **tin** sometimes. **Reasons:** It is fast. **Examples:** I heat it and **serve** it with bread." },
  { q: "Do you like **olives** on pizza?", a: "Yes, I like **olives** on pizza. **Reasons:** They add salty **flavour**. **Examples:** I choose pizza with **olives** and extra cheese." },
  { q: "Do you enjoy cooking with **herbs**?", a: "Yes, I enjoy cooking with **herb** flavours. **Reasons:** It makes food smell nice. **Examples:** I add a green **herb** to **tomato** **sauce**." },
  { q: "When you eat out, do you prefer sharing **several** dishes?", a: "Yes, I like sharing **several** dishes. **Reasons:** We can try **different** tastes. **Examples:** We order a **dish** for each person and share." },
  { q: "What is a food that tastes **bitter** to you?", a: "Some dark chocolate tastes **bitter** to me. **Reasons:** I prefer sweeter flavours. **Examples:** I choose milk chocolate instead." },
  { q: "What is a food that tastes **sour** to you?", a: "Lemon tastes **sour** to me. **Reasons:** It has strong acid. **Examples:** If I add lemon to **sauce**, it becomes **sour**." },
  { q: "Do you like a **thick** soup or a light soup?", a: "I like a **thick** soup. **Reasons:** It fills me up. **Examples:** I like a **thick** lentil **stew**." },
  { q: "What do you do with food you can’t finish at home?", a: "I keep it for later. **Reasons:** I don’t want to be **wasteful**. **Examples:** I put it in a **box** and eat it tomorrow." },
  { q: "What **mark** makes you feel proud?", a: "I feel proud of a high **mark**. **Reasons:** It shows my hard work. **Examples:** If I get 90%, I share it with my family." },
  { q: "Do you prefer drinks in **glass bottles** or **cans**?", a: "I prefer a **bottle**. **Reasons:** It feels cleaner and tastes better. **Examples:** I buy a **bottle** of water, not a **can**." },
  { q: "What do you do when you see a **shocking